---
title: "Clustering"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# init env
library(Seurat)
library(tidyverse)

extrafont::loadfonts()
theme_set(theme_linedraw(base_size = 12, base_family = "Arial"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# configs and functions
read_profile <- function (f){
    if (str_ends(f, ".rds")){
        df <- readRDS(f)
    }else if (str_ends(f, ".tsv")){
        df <- read_tsv(f)
    }else if (str_ends(f, ".xls") || str_ends(f, ".xlsx")){
        df <- readxl::read_excel(f)
    }else {
        stop(str_glue("Unrecognized file format: {f}\n"))
    }
    if (! "dataset" %in% colnames(df)){
        df["dataset"] <- str_remove(basename(f), "\\.[^.]+$")
    }
    res <- transmute(
        df, 
        dataset,
        ID = pick(
            any_of(c("description", "Description", "ID"))
        )[, 1, drop=TRUE],
        NES
    )
    return(res)
}
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# load data
df <- lapply(snakemake@input, read_profile) |>
    bind_rows()
```

## Heatmap

```{r echo=FALSE, message=FALSE, warning=FALSE}
pivot_wider(df, ID, names_from = dataset, values_from = NES) |>
    column_to_rownames("ID") |>
    pheatmap::pheatmap(
        clustering_distance_rows = "correlation",
        clustering_distance_cols = "correlation"
    )
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
dist_cosine <- function (x) {
    x <- as.matrix(x)
    sim <- x / sqrt(rowSums(x * x))
    sim <- sim %*% t(sim)
    as.dist(1 - sim)
}

pivot_wider(df, ID, names_from = dataset, values_from = NES) |>
    column_to_rownames("ID") |>
    t() |>
    dist_cosine() |>
    as.matrix() |>
    pheatmap::pheatmap()
```

## Cluster

```{r echo=FALSE, message=FALSE, warning=FALSE}
rds <- paste(snakemake@output[[1]], ".rds", sep = "")

if (file.exists(rds)){
    obj <- readRDS(rds)
}else {
    obj <- CreateAssayObject(
        data = pivot_wider(df, ID, names_from = dataset, values_from = NES, values_fill = 0L) |>
            column_to_rownames("ID") |>
            as.matrix()
    ) |>
        CreateSeuratObject(
            assay = "hallmark",
            names.delim = ":"
        ) |>
        FindVariableFeatures(nfeatures = 50) |>
        ScaleData() |>
        RunPCA(npcs = 20) |>
        RunUMAP(dims = 1:20, n.neighbors = 5) |>
        FindNeighbors(dims = 1:20, k.param = 5) |>
        FindClusters(resolution = snakemake@params[["resolution"]])
    
    saveRDS(obj, file = rds)
}

FetchData(obj, "ident") |>
    rownames_to_column("dataset") |>
    dplyr::rename(cluster = ident) |>
    write_tsv(paste(snakemake@output[[1]], ".tsv", sep = ""))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
FetchData(obj, c("UMAP_1", "UMAP_2", "ident")) |>
    rownames_to_column("dataset") |>
    ggplot(aes(UMAP_1, UMAP_2, color = ident)) +
        geom_point() +
        ggrepel::geom_text_repel(aes(label = dataset), seed = 1, size = 7/.pt,
            segment.size = 0.1, family = "Arial", max.iter = Inf, 
            min.segment.length = 0, max.overlaps = Inf
        ) +
        guides(color = "none")
```
