# Gencode annotation is going to be used for gene ID mapping.
# The Gencode release version.
# Choose the preferred Gencode annotation version from 
#   the available options listed here: https://www.gencodegenes.org/human/releases.html
gencode_version: "36"


# Available databases for enrichment analysis:
#  1. MSigDB
#  2. KEGG
#  3. GO_MF
#  4. GO_BP
#  5. Custom pathway term-gene mapping file in the TSV format
#       with at least two columns,
#       one for the pathway term (ID and/or description),
#       and one for the gene (ensembl, entrez, and/or symbol).
#       For example:
#       ID        entrez    description
#       hsa01100  10        Metabolic pathways
#       hsa01100  100       Metabolic pathways
enrichment_analysis_database: MSigDB


# Custom dataset registration.
datasets:
  custom_1: # Dataset name
    # Risk profile file in the gene level.
    # The file can be an R Data, TSV, or XLSX, with at least three columns:
    #   1. gene ID, such as `ensembl` (Ensembl gene ID), `entrez` (NCBI Entrez gene ID), and / or `symbol` (gene symbol)
    #   2. `beta`, the effect size, such as survival log hazard ratio and correlation coefficient
    #   3. `pval`, the statistical P-value associated with the `beta` value
    gene: "path/to/gene_level_risk_profile"
  AOR_vs_MAM: # An example
    gene: "custom/AOR_vs_MAM_DGElist.xlsx"
  custom_2: # Dataset name
    # Risk profile file in the pathway level.
    # Use this with caution, due to potential misalignment of the enrichment database.
    # The file can be an R Data, TSV, or XLSX, with at least two columns:
    #   1. `ID`, the pathway ID
    #   2. `NES`, the normalized enrichment score calculated by GSEA
    pathway: "path/to/pathway_level_risk_profile"


# Criteria to remove noise and outlier genes.
## General criteria
pvalue_range:
  - 0
  - 0.5
beta_range:
  - "-Inf"
  - "Inf"
## Dataset specific criteria,
##   which will overwrite the corresponding general criteria
bike_plaque:
  beta_range:
    - -10
    - 10
bike_pbmc:
  beta_range:
    - -10
    - 10
tcga:
  beta_range:
    - -10
    - 10


# Clustering parameters.
# This part configures which datasets will be included in the clustering analysis,
#   and how densely clustered datasets are grouped together.
# Configurations for multiple analyses are allowed.
dataset_clustering:

  cancer_only: # Analysis name, as prefix to the corresponding output filenames
    datasets: # The list of datasets included in the analysis
      [
        "ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", 
        "ESCA", "GBM", "HNSC", "KIRC", "KIRP", "LAML", "LGG",
        "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "READ",
         "SARC", "SKCM", "STAD", "THCA", "UCEC", "UCS", "UVM"
      ]
    # The resolution parameter controls the granularity of clustering.
    # Higher values (above 1.0) lead to a larger number of communities, 
    #   while lower values (below 1.0) result in a smaller number of communities.
    # The optimal value depends on the specific goals.
    # For details, see https://satijalab.org/seurat/reference/findclusters
    resolution: 1
  
  athero_and_cancer: # Another analysis name
    datasets:
      [
        "AOR_vs_MAM", "AOR_duke", "AOR_syntax", "bike_plaque",
        "ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", 
        "ESCA", "GBM", "HNSC", "KIRC", "KIRP", "LAML", "LGG",
        "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "READ",
         "SARC", "SKCM", "STAD", "THCA", "UCEC", "UCS", "UVM"
      ]
    resolution: 0.4


# Dataset group definition.
# The grouping configuration may depend on dataset clustering results.
# Here is the chance to assign meaningful names to each cluster after dataset clustering.
dataset_grouping:

  cancer_clusters: # Analysis name, as prefix to the corresponding output filenames
    inflammatory: ["BRCA" , "CESC" , "GBM" , "LGG" , "LUSC" , "OV" , "PAAD" , "READ" , "STAD" , "THCA"]
    proliferative: ["ACC" , "BLCA" , "COAD" , "KIRC" , "KIRP" , "LUAD" , "MESO" , "SARC" , "SKCM" , "UCEC"]
    metabolic: ["CHOL" , "ESCA" , "HNSC" , "LAML" , "LIHC" , "UCS" , "UVM"]
  
  athero_vs_cancer: # Another analysis name
    atherosclerosis: ["AOR_vs_MAM", "AOR_duke", "AOR_syntax", "bike_plaque"]
    cancer: ["ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", 
        "ESCA", "GBM", "HNSC", "KIRC", "KIRP", "LAML", "LGG",
        "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "READ",
         "SARC", "SKCM", "STAD", "THCA", "UCEC", "UCS", "UVM"
      ]
  
  athero_vs_cancer2: # Another analysis name
    atherosclerosis: ["AOR_vs_MAM", "AOR_duke", "AOR_syntax", "bike_plaque"]
    athero_similar: ["BRCA", "CESC", "GBM", "LGG", "LUSC", "OV", "PAAD", "READ", "STAD", "THCA"]
    athero_dissimilar: ["ACC", "BLCA", "COAD", "KIRC", "KIRP", "LUAD", "MESO", "SARC",
      "SKCM", "UCEC", "CHOL", "ESCA", "HNSC", "LAML", "UCS", "UVM"]